<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.holon-platform.jdbc</groupId>
		<artifactId>holon-jdbc-root</artifactId>
		<version>12.0.0</version>
	</parent>

	<artifactId>holon-starter-jdbc</artifactId>
	<packaging>jar</packaging>

	<name>${project.groupId}:${project.artifactId}</name>
	<description>Holon Spring Boot JDBC starter</description>

	<url>https://holon-platform.com</url>

	<dependencies>

		<!-- Holon base Spring Boot starter -->
		<dependency>
			<groupId>com.holon-platform.core</groupId>
			<artifactId>holon-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>ch.qos.logback</groupId>
					<artifactId>logback-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>ch.qos.logback</groupId>
					<artifactId>logback-classic</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- Holon JDBC Spring Boot -->
		<dependency>
			<groupId>com.holon-platform.jdbc</groupId>
			<artifactId>holon-jdbc-spring-boot</artifactId>
		</dependency>

		<!-- Logback aligned through parent dependencyManagement -->
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
		</dependency>

	</dependencies>

</project>